# Generated by Django 5.0.6 on 2024-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='pressur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FMALE', 'F/Male')], max_length=10)),
            ],
        ),
    ]
