# Generated by Django 5.0.6 on 2024-07-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review_delete_pressur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
