# Generated by Django 5.0.6 on 2024-07-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="store.customer",
            ),
        ),
    ]
